// pkg/renderer/component_markdown.go
package renderer

import (
	"fmt"
	"strings"
)

const autoGenHeader = "<!-- Auto-generated by architecture-analyzer. Do not edit. -->\n"

// RenderComponentMarkdown produces a single comprehensive markdown file for a
// component, including all extracted fields. Sections with no data are omitted.
func RenderComponentMarkdown(data map[string]interface{}) string {
	var b strings.Builder

	component := getStr(data, "component", "unknown")

	b.WriteString(autoGenHeader)
	b.WriteString(fmt.Sprintf("# %s\n\n", component))

	// Summary blockquote
	if summary := getStr(data, "summary", ""); summary != "" {
		b.WriteString(fmt.Sprintf("> %s\n\n", summary))
	}

	// Metadata (always present)
	renderMetadataSection(&b, data)

	// Sections from existing report.go coverage (conditional)
	renderCMDSection(&b, data, "CRDs", "crds", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Kind | Group | Version | Scope | Fields | Validation Rules | Source |\n")
		b.WriteString("|------|-------|---------|-------|--------|------------------|--------|\n")
		for _, crd := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %d | %s | %s |\n",
				escapeMdCell(getStr(crd, "kind", "")),
				escapeMdCell(getStr(crd, "group", "")),
				escapeMdCell(getStr(crd, "version", "")),
				escapeMdCell(getStr(crd, "scope", "")),
				getInt(crd, "fields_count"),
				escapeMdCell(strings.Join(getStringSlice(crd, "validation_rules"), ", ")),
				sourceLink(data, getStr(crd, "source", "")),
			))
		}
	})

	renderCMDSection(&b, data, "Webhooks", "webhooks", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Type | Resources | Operations | Source |\n")
		b.WriteString("|------|------|-----------|------------|--------|\n")
		for _, wh := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				escapeMdCell(getStr(wh, "name", "")),
				escapeMdCell(getStr(wh, "type", "")),
				escapeMdCell(strings.Join(getStringSlice(wh, "resources"), ", ")),
				escapeMdCell(strings.Join(getStringSlice(wh, "operations"), ", ")),
				sourceLink(data, getStr(wh, "source", "")),
			))
		}
	})

	renderCMDSection(&b, data, "HTTP Endpoints", "http_endpoints", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Method | Path | Description | Source |\n")
		b.WriteString("|--------|------|-------------|--------|\n")
		for _, ep := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(ep, "method", "")),
				escapeMdCell(getStr(ep, "path", "")),
				escapeMdCell(getStr(ep, "description", "")),
				sourceLink(data, getStr(ep, "source", "")),
			))
		}
	})

	renderCMDSection(&b, data, "Services", "services", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Type | Ports | Source |\n")
		b.WriteString("|------|------|-------|--------|\n")
		for _, svc := range items {
			ports := formatPorts(getSlice(svc, "ports"))
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(svc, "name", "")),
				escapeMdCell(getStr(svc, "type", "")),
				escapeMdCell(ports),
				sourceLink(data, getStr(svc, "source", "")),
			))
		}
	})

	renderCMDSection(&b, data, "Ingress Routing", "ingress_routing", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Host | Path | Backend |\n")
		b.WriteString("|------|------|------|---------|\n")
		for _, ing := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(ing, "name", "")),
				escapeMdCell(getStr(ing, "host", "")),
				escapeMdCell(getStr(ing, "path", "")),
				escapeMdCell(getStr(ing, "backend", "")),
			))
		}
	})

	renderCMDSection(&b, data, "Network Policies", "network_policies", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Pod Selector | Ingress Rules | Egress Rules |\n")
		b.WriteString("|------|-------------|---------------|--------------|\n")
		for _, np := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %d | %d |\n",
				escapeMdCell(getStr(np, "name", "")),
				escapeMdCell(getStr(np, "pod_selector", "")),
				getInt(np, "ingress_rule_count"),
				getInt(np, "egress_rule_count"),
			))
		}
	})

	renderCMDSection(&b, data, "Deployments", "deployments", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Containers | Images |\n")
		b.WriteString("|------|-----------|--------|\n")
		for _, dep := range items {
			containers := getSlice(dep, "containers")
			names := make([]string, 0, len(containers))
			images := make([]string, 0, len(containers))
			for _, c := range containers {
				names = append(names, getStr(c, "name", ""))
				images = append(images, getStr(c, "image", ""))
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(dep, "name", "")),
				escapeMdCell(strings.Join(names, ", ")),
				escapeMdCell(strings.Join(images, ", ")),
			))
		}
	})

	// RBAC section (composite)
	renderRBACMarkdownSection(&b, data)

	renderCMDSection(&b, data, "Secrets Referenced", "secrets_referenced", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Type | Mount Path | Source |\n")
		b.WriteString("|------|------|------------|--------|\n")
		for _, s := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(s, "name", "")),
				escapeMdCell(getStr(s, "type", "")),
				escapeMdCell(getStr(s, "mount_path", "")),
				sourceLink(data, getStr(s, "source", "")),
			))
		}
	})

	// Security contexts (extracted from deployments)
	renderSecurityContextMarkdownSection(&b, data)

	// Dependencies section (composite)
	renderDependenciesMarkdownSection(&b, data)

	renderCMDSection(&b, data, "Controller Watches", "controller_watches", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| GVK | Watch Type | Source |\n")
		b.WriteString("|-----|-----------|--------|\n")
		for _, w := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(w, "gvk", "")),
				escapeMdCell(getStr(w, "type", "")),
				sourceLink(data, getStr(w, "source", "")),
			))
		}
	})

	// ConfigMaps
	renderCMDSection(&b, data, "ConfigMaps", "configmaps", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Data Keys | Source |\n")
		b.WriteString("|------|-----------|--------|\n")
		for _, cm := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(cm, "name", "")),
				escapeMdCell(strings.Join(getStringSlice(cm, "data_keys"), ", ")),
				sourceLink(data, getStr(cm, "source", "")),
			))
		}
	})

	// Helm
	renderHelmMarkdownSection(&b, data)

	// Dockerfiles
	renderCMDSection(&b, data, "Dockerfiles", "dockerfiles", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Path | Base Image | Stages | Exposed Ports |\n")
		b.WriteString("|------|-----------|--------|---------------|\n")
		for _, df := range items {
			ports := getStringSlice(df, "exposed_ports")
			portStr := ""
			if len(ports) > 0 {
				portStr = strings.Join(ports, ", ")
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %d | %s |\n",
				escapeMdCell(getStr(df, "path", "")),
				escapeMdCell(getStr(df, "base_image", "")),
				getInt(df, "stage_count"),
				escapeMdCell(portStr),
			))
		}
	})

	// Cache architecture
	renderCacheMarkdownSection(&b, data)

	// --- NEW SECTIONS (24 unrendered fields) ---

	// Component References
	renderCMDSection(&b, data, "Component References", "component_refs", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Target | Type | Source | Evidence |\n")
		b.WriteString("|--------|------|--------|----------|\n")
		for _, ref := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(ref, "target", "")),
				escapeMdCell(getStr(ref, "type", "")),
				escapeMdCell(getStr(ref, "source", "")),
				escapeMdCell(getStr(ref, "evidence", "")),
			))
		}
	})

	// Operator Config
	renderOperatorConfigMarkdownSection(&b, data)

	// API Types
	renderCMDSection(&b, data, "API Types", "api_types", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Type Name | Kind | Fields | Spec? | Source |\n")
		b.WriteString("|-----------|------|--------|-------|--------|\n")
		for _, at := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %d | %v | %s |\n",
				escapeMdCell(getStr(at, "name", "")),
				escapeMdCell(getStr(at, "kind", "")),
				getInt(at, "fields_count"),
				getBool(at, "is_spec", false),
				sourceLink(data, getStr(at, "source", "")),
			))
		}
	})

	// Reconciliation Sequences
	renderReconcileSequencesMarkdownSection(&b, data)

	// Prometheus Metrics
	renderCMDSection(&b, data, "Prometheus Metrics", "prometheus_metrics", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Type | Help | Source |\n")
		b.WriteString("|------|------|------|--------|\n")
		for _, pm := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(pm, "name", "")),
				escapeMdCell(getStr(pm, "type", "")),
				escapeMdCell(getStr(pm, "help", "")),
				sourceLink(data, getStr(pm, "source", "")),
			))
		}
	})

	// Status Conditions
	renderCMDSection(&b, data, "Status Conditions", "status_conditions", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Type | Reason | Status | Message |\n")
		b.WriteString("|------|--------|--------|---------|\n")
		for _, sc := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(sc, "type", "")),
				escapeMdCell(getStr(sc, "reason", "")),
				escapeMdCell(getStr(sc, "status", "")),
				escapeMdCell(getStr(sc, "message", "")),
			))
		}
	})

	// Feature Gates
	renderCMDSection(&b, data, "Feature Gates", "feature_gates", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Default | Stage | Source |\n")
		b.WriteString("|------|---------|-------|--------|\n")
		for _, fg := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(fg, "name", "")),
				escapeMdCell(getStr(fg, "default", "")),
				escapeMdCell(getStr(fg, "stage", "")),
				sourceLink(data, getStr(fg, "source", "")),
			))
		}
	})

	// Serving Runtimes
	renderCMDSection(&b, data, "Serving Runtimes", "serving_runtimes", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Protocol | Containers |\n")
		b.WriteString("|------|----------|------------|\n")
		for _, sr := range items {
			containers := getSlice(sr, "containers")
			names := make([]string, 0, len(containers))
			for _, c := range containers {
				names = append(names, getStr(c, "name", ""))
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(sr, "name", "")),
				escapeMdCell(getStr(sr, "protocol", "")),
				escapeMdCell(strings.Join(names, ", ")),
			))
		}
	})

	// Serving Runtime References
	renderCMDSection(&b, data, "Serving Runtime References", "serving_runtime_refs", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Runtime | CRD Kind | Source |\n")
		b.WriteString("|---------|----------|--------|\n")
		for _, srr := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(srr, "runtime", "")),
				escapeMdCell(getStr(srr, "crd_kind", "")),
				sourceLink(data, getStr(srr, "source", "")),
			))
		}
	})

	// Label Contracts
	renderCMDSection(&b, data, "Label Contracts", "label_contracts", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Key | Value | Integration | Scope |\n")
		b.WriteString("|-----|-------|-------------|-------|\n")
		for _, lc := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(getStr(lc, "key", "")),
				escapeMdCell(getStr(lc, "value", "")),
				escapeMdCell(getStr(lc, "integration", "")),
				escapeMdCell(getStr(lc, "scope", "")),
			))
		}
	})

	// Kustomize Overlays
	renderCMDSection(&b, data, "Kustomize Overlays", "kustomize_overlay_refs", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Overlay | Base | Components |\n")
		b.WriteString("|---------|------|------------|\n")
		for _, ko := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(ko, "overlay", "")),
				escapeMdCell(getStr(ko, "base", "")),
				escapeMdCell(strings.Join(getStringSlice(ko, "components"), ", ")),
			))
		}
	})

	// Kustomize Components
	renderCMDSection(&b, data, "Kustomize Components", "kustomize_components", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Path | Source |\n")
		b.WriteString("|------|------|--------|\n")
		for _, kc := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(kc, "name", "")),
				escapeMdCell(getStr(kc, "path", "")),
				sourceLink(data, getStr(kc, "source", "")),
			))
		}
	})

	// ConfigMap Volumes
	renderCMDSection(&b, data, "ConfigMap Volumes", "configmap_volumes", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| ConfigMap | Mount Path | Deployment |\n")
		b.WriteString("|-----------|-----------|------------|\n")
		for _, cv := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(cv, "configmap_name", "")),
				escapeMdCell(getStr(cv, "mount_path", "")),
				escapeMdCell(getStr(cv, "deployment", "")),
			))
		}
	})

	// Pod Disruption Budgets
	renderCMDSection(&b, data, "Pod Disruption Budgets", "pod_disruption_budgets", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Min Available | Max Unavailable |\n")
		b.WriteString("|------|--------------|------------------|\n")
		for _, pdb := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(pdb, "name", "")),
				escapeMdCell(getStr(pdb, "min_available", "")),
				escapeMdCell(getStr(pdb, "max_unavailable", "")),
			))
		}
	})

	// Horizontal Pod Autoscalers
	renderCMDSection(&b, data, "Horizontal Pod Autoscalers", "horizontal_pod_autoscalers", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Name | Min Replicas | Max Replicas | Metrics |\n")
		b.WriteString("|------|-------------|-------------|---------|\n")
		for _, hpa := range items {
			metrics := getStringSlice(hpa, "metrics")
			b.WriteString(fmt.Sprintf("| %s | %d | %d | %s |\n",
				escapeMdCell(getStr(hpa, "name", "")),
				getInt(hpa, "min_replicas"),
				getInt(hpa, "max_replicas"),
				escapeMdCell(strings.Join(metrics, ", ")),
			))
		}
	})

	// Python K8s API Calls
	renderCMDSection(&b, data, "Python K8s API Calls", "python_k8s_calls", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Operation | Resource Kind | Source |\n")
		b.WriteString("|-----------|-------------|--------|\n")
		for _, call := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(call, "operation", "")),
				escapeMdCell(getStr(call, "resource_kind", "")),
				sourceLink(data, getStr(call, "source", "")),
			))
		}
	})

	// Template Files
	renderCMDSection(&b, data, "Template Files", "template_files", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Path | Type | Variables |\n")
		b.WriteString("|------|------|-----------|\n")
		for _, tf := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %d |\n",
				escapeMdCell(getStr(tf, "path", "")),
				escapeMdCell(getStr(tf, "type", "")),
				getInt(tf, "variable_count"),
			))
		}
	})

	// Resource Defaults
	renderCMDSection(&b, data, "Resource Defaults", "resource_defaults", func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{}) {
		b.WriteString("| Resource | CPU Request | Memory Request | CPU Limit | Memory Limit |\n")
		b.WriteString("|----------|------------|----------------|-----------|-------------|\n")
		for _, rd := range items {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				escapeMdCell(getStr(rd, "resource", "")),
				escapeMdCell(getStr(rd, "cpu_request", "")),
				escapeMdCell(getStr(rd, "memory_request", "")),
				escapeMdCell(getStr(rd, "cpu_limit", "")),
				escapeMdCell(getStr(rd, "memory_limit", "")),
			))
		}
	})

	// Platform Detection
	renderPlatformDetectionMarkdownSection(&b, data)

	return b.String()
}

// renderCMDSection is a generic conditional section renderer.
// It only emits the section if the key exists and has items.
type sectionRenderFn func(b *strings.Builder, items []map[string]interface{}, data map[string]interface{})

func renderCMDSection(b *strings.Builder, data map[string]interface{}, title, key string, fn sectionRenderFn) {
	items := getSlice(data, key)
	if len(items) == 0 {
		return
	}
	b.WriteString(fmt.Sprintf("\n## %s\n\n", title))
	fn(b, items, data)
	b.WriteString("\n")
}

// renderMetadataSection always renders the metadata table.
func renderMetadataSection(b *strings.Builder, data map[string]interface{}) {
	b.WriteString("\n## Metadata\n\n")
	b.WriteString("| Field | Value |\n")
	b.WriteString("|-------|-------|\n")
	b.WriteString(fmt.Sprintf("| Repository | %s |\n", escapeMdCell(getStr(data, "repo", ""))))
	aliases := getStringSlice(data, "aliases")
	if len(aliases) > 0 {
		b.WriteString(fmt.Sprintf("| Aliases | %s |\n", escapeMdCell(strings.Join(aliases, ", "))))
	}
	if sha := getStr(data, "commit_sha", ""); sha != "" {
		b.WriteString(fmt.Sprintf("| Commit | %s |\n", escapeMdCell(sha)))
	}
	b.WriteString(fmt.Sprintf("| Extracted | %s |\n", escapeMdCell(getStr(data, "extracted_at", ""))))
	b.WriteString(fmt.Sprintf("| Analyzer Version | %s |\n", escapeMdCell(getStr(data, "analyzer_version", ""))))
	dc := getMap(data, "data_coverage")
	if dc != nil {
		status := getStr(dc, "status", "full")
		b.WriteString(fmt.Sprintf("| Data Coverage | %s |\n", escapeMdCell(status)))
	}
	b.WriteString("\n")
}

// renderRBACMarkdownSection renders RBAC with conditional sub-sections.
func renderRBACMarkdownSection(b *strings.Builder, data map[string]interface{}) {
	rbac := getMap(data, "rbac")
	if rbac == nil {
		return
	}
	clusterRoles := getSlice(rbac, "cluster_roles")
	clusterBindings := getSlice(rbac, "cluster_role_bindings")
	markers := getSlice(rbac, "kubebuilder_markers")
	roles := getSlice(rbac, "roles")
	roleBindings := getSlice(rbac, "role_bindings")
	if len(clusterRoles) == 0 && len(clusterBindings) == 0 && len(markers) == 0 && len(roles) == 0 && len(roleBindings) == 0 {
		return
	}
	b.WriteString("\n## RBAC\n\n")
	if len(clusterRoles) > 0 {
		b.WriteString("### Cluster Roles\n\n")
		b.WriteString("| Name | Rules Summary | Source |\n")
		b.WriteString("|------|---------------|--------|\n")
		for _, cr := range clusterRoles {
			summary := computeRoleSummary(cr, "ClusterRole")
			summaryStr := fmt.Sprintf("%d resources", summary.ResourceCount)
			if summary.HasWildcard {
				summaryStr += " (wildcard)"
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(cr, "name", "")),
				escapeMdCell(summaryStr),
				sourceLink(data, getStr(cr, "source", "")),
			))
		}
		b.WriteString("\n")
	}
	if len(clusterBindings) > 0 {
		b.WriteString("### Cluster Role Bindings\n\n")
		b.WriteString("| Name | Role Ref | Subjects |\n")
		b.WriteString("|------|----------|----------|\n")
		for _, crb := range clusterBindings {
			subjects := getSlice(crb, "subjects")
			subjectNames := make([]string, 0, len(subjects))
			for _, s := range subjects {
				subjectNames = append(subjectNames, getStr(s, "name", ""))
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(crb, "name", "")),
				escapeMdCell(getStr(crb, "role_ref", "")),
				escapeMdCell(strings.Join(subjectNames, ", ")),
			))
		}
		b.WriteString("\n")
	}
	if len(roles) > 0 {
		b.WriteString("### Roles\n\n")
		b.WriteString("| Name | Rules Summary | Source |\n")
		b.WriteString("|------|---------------|--------|\n")
		for _, r := range roles {
			summary := computeRoleSummary(r, "Role")
			summaryStr := fmt.Sprintf("%d resources", summary.ResourceCount)
			if summary.HasWildcard {
				summaryStr += " (wildcard)"
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(r, "name", "")),
				escapeMdCell(summaryStr),
				sourceLink(data, getStr(r, "source", "")),
			))
		}
		b.WriteString("\n")
	}
	if len(roleBindings) > 0 {
		b.WriteString("### Role Bindings\n\n")
		b.WriteString("| Name | Role Ref | Subjects |\n")
		b.WriteString("|------|----------|----------|\n")
		for _, rb := range roleBindings {
			subjects := getSlice(rb, "subjects")
			subjectNames := make([]string, 0, len(subjects))
			for _, s := range subjects {
				subjectNames = append(subjectNames, getStr(s, "name", ""))
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(rb, "name", "")),
				escapeMdCell(getStr(rb, "role_ref", "")),
				escapeMdCell(strings.Join(subjectNames, ", ")),
			))
		}
		b.WriteString("\n")
	}
	if len(markers) > 0 {
		b.WriteString("### Kubebuilder RBAC Markers\n\n")
		b.WriteString("| Groups | Resources | Verbs | Source |\n")
		b.WriteString("|--------|-----------|-------|--------|\n")
		for _, m := range markers {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				escapeMdCell(strings.Join(getStringSlice(m, "groups"), ", ")),
				escapeMdCell(strings.Join(getStringSlice(m, "resources"), ", ")),
				escapeMdCell(strings.Join(getStringSlice(m, "verbs"), ", ")),
				sourceLink(data, getStr(m, "source", "")),
			))
		}
		b.WriteString("\n")
	}
}

// renderSecurityContextMarkdownSection extracts security contexts from deployments.
func renderSecurityContextMarkdownSection(b *strings.Builder, data map[string]interface{}) {
	deployments := getSlice(data, "deployments")
	type secCtx struct {
		container    string
		runAsNonRoot string
		readOnlyFS   string
		capabilities string
	}
	var contexts []secCtx
	for _, dep := range deployments {
		for _, c := range getSlice(dep, "containers") {
			sc := getMap(c, "security_context")
			if sc == nil {
				continue
			}
			contexts = append(contexts, secCtx{
				container:    getStr(c, "name", ""),
				runAsNonRoot: fmt.Sprintf("%v", getBool(sc, "run_as_non_root", false)),
				readOnlyFS:   fmt.Sprintf("%v", getBool(sc, "read_only_root_filesystem", false)),
				capabilities: strings.Join(getStringSlice(sc, "drop_capabilities"), ", "),
			})
		}
	}
	if len(contexts) == 0 {
		return
	}
	b.WriteString("\n## Security Contexts\n\n")
	b.WriteString("| Container | RunAsNonRoot | ReadOnlyFS | Capabilities |\n")
	b.WriteString("|-----------|-------------|------------|--------------|\n")
	for _, sc := range contexts {
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
			escapeMdCell(sc.container), sc.runAsNonRoot, sc.readOnlyFS, escapeMdCell(sc.capabilities)))
	}
	b.WriteString("\n")
}

// renderDependenciesMarkdownSection renders the composite dependencies section.
func renderDependenciesMarkdownSection(b *strings.Builder, data map[string]interface{}) {
	deps := getMap(data, "dependencies")
	extConns := getSlice(data, "external_connections")
	runtimeDeps := getSlice(data, "runtime_dependencies")
	pythonPkgs := []map[string]interface{}(nil)
	var goModules, internalODH []map[string]interface{}
	if deps != nil {
		goModules = getSlice(deps, "go_modules")
		internalODH = getSlice(deps, "internal_odh")
		pythonPkgs = getSlice(deps, "python_packages")
	}
	if len(goModules) == 0 && len(internalODH) == 0 && len(pythonPkgs) == 0 && len(extConns) == 0 && len(runtimeDeps) == 0 {
		return
	}
	b.WriteString("\n## Dependencies\n\n")
	if len(internalODH) > 0 {
		b.WriteString("### Internal ODH Components\n\n")
		for _, dep := range internalODH {
			b.WriteString(fmt.Sprintf("- %s\n", getStr(dep, "component", "")))
		}
		b.WriteString("\n")
	}
	if len(goModules) > 0 {
		b.WriteString("### Go Modules\n\n")
		b.WriteString("| Module | Version |\n")
		b.WriteString("|--------|---------|\n")
		for _, mod := range goModules {
			b.WriteString(fmt.Sprintf("| %s | %s |\n",
				escapeMdCell(getStr(mod, "path", getStr(mod, "module", ""))),
				escapeMdCell(getStr(mod, "version", "")),
			))
		}
		b.WriteString("\n")
	}
	if len(pythonPkgs) > 0 {
		b.WriteString("### Python Packages\n\n")
		b.WriteString("| Package | Version | Category | Required |\n")
		b.WriteString("|---------|---------|----------|----------|\n")
		for _, pkg := range pythonPkgs {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %v |\n",
				escapeMdCell(getStr(pkg, "name", "")),
				escapeMdCell(getStr(pkg, "version", "")),
				escapeMdCell(getStr(pkg, "category", "")),
				getBool(pkg, "required", false),
			))
		}
		b.WriteString("\n")
	}
	if len(extConns) > 0 {
		b.WriteString("### External Connections\n\n")
		b.WriteString("| Service | Type | Evidence |\n")
		b.WriteString("|---------|------|----------|\n")
		for _, ec := range extConns {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(ec, "service", "")),
				escapeMdCell(getStr(ec, "type", "")),
				escapeMdCell(getStr(ec, "evidence", "")),
			))
		}
		b.WriteString("\n")
	}
	if len(runtimeDeps) > 0 {
		b.WriteString("### Runtime Dependencies\n\n")
		b.WriteString("| Name | Type | Evidence |\n")
		b.WriteString("|------|------|----------|\n")
		for _, rd := range runtimeDeps {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(rd, "name", "")),
				escapeMdCell(getStr(rd, "type", "")),
				escapeMdCell(getStr(rd, "evidence", "")),
			))
		}
		b.WriteString("\n")
	}
}

// renderHelmMarkdownSection renders helm chart info if present.
func renderHelmMarkdownSection(b *strings.Builder, data map[string]interface{}) {
	helm := getMap(data, "helm")
	if helm == nil {
		return
	}
	charts := getSlice(helm, "charts")
	if len(charts) == 0 {
		return
	}
	b.WriteString("\n## Helm\n\n")
	b.WriteString("| Chart | Version | Values |\n")
	b.WriteString("|-------|---------|--------|\n")
	for _, ch := range charts {
		b.WriteString(fmt.Sprintf("| %s | %s | %d |\n",
			escapeMdCell(getStr(ch, "name", "")),
			escapeMdCell(getStr(ch, "version", "")),
			getInt(ch, "values_count"),
		))
	}
	b.WriteString("\n")
}

// renderCacheMarkdownSection renders cache architecture if present.
func renderCacheMarkdownSection(b *strings.Builder, data map[string]interface{}) {
	cache := getMap(data, "cache_config")
	if cache == nil {
		return
	}
	b.WriteString("\n## Cache Architecture\n\n")
	if mgr := getStr(cache, "manager_type", ""); mgr != "" {
		b.WriteString(fmt.Sprintf("**Manager Type:** %s\n\n", mgr))
	}
	filtered := getSlice(cache, "filtered_types")
	if len(filtered) > 0 {
		b.WriteString("**Filtered Types:**\n")
		for _, ft := range filtered {
			b.WriteString(fmt.Sprintf("- %s\n", getStr(ft, "gvk", "")))
		}
		b.WriteString("\n")
	}
}

// renderOperatorConfigMarkdownSection renders operator config split by category.
func renderOperatorConfigMarkdownSection(b *strings.Builder, data map[string]interface{}) {
	items := getSlice(data, "operator_config")
	if len(items) == 0 {
		return
	}
	b.WriteString("\n## Operator Config\n\n")
	images := make([]map[string]interface{}, 0)
	envVars := make([]map[string]interface{}, 0)
	other := make([]map[string]interface{}, 0)
	for _, oc := range items {
		switch getStr(oc, "category", "") {
		case "image":
			images = append(images, oc)
		case "env_var":
			envVars = append(envVars, oc)
		default:
			other = append(other, oc)
		}
	}
	renderConfigSubTable := func(title string, entries []map[string]interface{}) {
		if len(entries) == 0 {
			return
		}
		b.WriteString(fmt.Sprintf("### %s\n\n", title))
		b.WriteString("| Name | Value | Source |\n")
		b.WriteString("|------|-------|--------|\n")
		for _, e := range entries {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				escapeMdCell(getStr(e, "name", "")),
				escapeMdCell(getStr(e, "value", "")),
				sourceLink(data, getStr(e, "source", "")),
			))
		}
		b.WriteString("\n")
	}
	renderConfigSubTable("Image References", images)
	renderConfigSubTable("Environment Variables", envVars)
	renderConfigSubTable("Other Constants", other)
}

// renderReconcileSequencesMarkdownSection renders reconciliation step sequences.
func renderReconcileSequencesMarkdownSection(b *strings.Builder, data map[string]interface{}) {
	seqs := getSlice(data, "reconcile_sequences")
	if len(seqs) == 0 {
		return
	}
	b.WriteString("\n## Reconciliation Sequences\n\n")
	for _, seq := range seqs {
		controller := getStr(seq, "controller", "unknown")
		b.WriteString(fmt.Sprintf("### %s\n\n", controller))
		steps := getSlice(seq, "steps")
		for i, step := range steps {
			b.WriteString(fmt.Sprintf("%d. %s (%s)\n",
				i+1,
				getStr(step, "method", ""),
				getStr(step, "resource_kind", ""),
			))
		}
		b.WriteString("\n")
	}
}

// renderPlatformDetectionMarkdownSection renders platform detection conditionals.
func renderPlatformDetectionMarkdownSection(b *strings.Builder, data map[string]interface{}) {
	pd := getMap(data, "platform_detection")
	if pd == nil {
		return
	}
	conditionals := getSlice(pd, "conditionals")
	if len(conditionals) == 0 {
		return
	}
	b.WriteString("\n## Platform Detection\n\n")
	b.WriteString("| Check | Type | Evidence |\n")
	b.WriteString("|-------|------|----------|\n")
	for _, c := range conditionals {
		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
			escapeMdCell(getStr(c, "check", "")),
			escapeMdCell(getStr(c, "type", "")),
			escapeMdCell(getStr(c, "evidence", "")),
		))
	}
	b.WriteString("\n")
}

// formatPorts formats port entries for display.
func formatPorts(ports []map[string]interface{}) string {
	parts := make([]string, 0, len(ports))
	for _, p := range ports {
		port := getInt(p, "port")
		proto := getStr(p, "protocol", "TCP")
		name := getStr(p, "name", "")
		if name != "" {
			parts = append(parts, fmt.Sprintf("%d/%s (%s)", port, proto, name))
		} else {
			parts = append(parts, fmt.Sprintf("%d/%s", port, proto))
		}
	}
	return strings.Join(parts, ", ")
}
