// pkg/renderer/component_markdown_test.go
package renderer

import (
	"strings"
	"testing"
)

func TestRenderComponentMarkdown_BasicStructure(t *testing.T) {
	data := map[string]interface{}{
		"component":        "test-component",
		"repo":             "github.com/org/test-component",
		"commit_sha":       "abc123",
		"extracted_at":     "2026-05-08T00:00:00Z",
		"analyzer_version": "1.0.0",
		"summary":          "test-component is a Kubernetes component managing 2 CRDs.",
		"crds": []interface{}{
			map[string]interface{}{
				"kind":    "TestResource",
				"group":   "test.example.com",
				"version": "v1",
				"scope":   "Namespaced",
				"source":  "api/v1/types.go:10",
			},
		},
		"services": []interface{}{
			map[string]interface{}{
				"name": "test-svc",
				"type": "ClusterIP",
				"ports": []interface{}{
					map[string]interface{}{"port": float64(8080), "protocol": "TCP"},
				},
				"source": "config/default/service.yaml:1",
			},
		},
	}

	result := RenderComponentMarkdown(data)

	if !strings.HasPrefix(result, "<!-- Auto-generated by architecture-analyzer. Do not edit. -->") {
		t.Error("missing auto-generated header")
	}
	if !strings.Contains(result, "# test-component") {
		t.Error("missing component heading")
	}
	if !strings.Contains(result, "> test-component is a Kubernetes component") {
		t.Error("missing summary blockquote")
	}
	if !strings.Contains(result, "## CRDs") {
		t.Error("missing CRDs section")
	}
	if !strings.Contains(result, "TestResource") {
		t.Error("missing CRD kind in table")
	}
	if !strings.Contains(result, "## Services") {
		t.Error("missing Services section")
	}
	if !strings.Contains(result, "test-svc") {
		t.Error("missing service name in table")
	}
}

func TestRenderComponentMarkdown_EmptySectionsOmitted(t *testing.T) {
	data := map[string]interface{}{
		"component":        "minimal",
		"repo":             "github.com/org/minimal",
		"extracted_at":     "2026-05-08T00:00:00Z",
		"analyzer_version": "1.0.0",
	}

	result := RenderComponentMarkdown(data)

	if strings.Contains(result, "## CRDs") {
		t.Error("CRDs section should be omitted when empty")
	}
	if strings.Contains(result, "## Services") {
		t.Error("Services section should be omitted when empty")
	}
	if strings.Contains(result, "## RBAC") {
		t.Error("RBAC section should be omitted when empty")
	}
	if !strings.Contains(result, "# minimal") {
		t.Error("missing component heading")
	}
	if !strings.Contains(result, "## Metadata") {
		t.Error("missing Metadata section")
	}
}

func TestRenderComponentMarkdown_SourceLinks(t *testing.T) {
	data := map[string]interface{}{
		"component":  "linked",
		"repo":       "org/repo",
		"commit_sha": "abc123",
		"crds": []interface{}{
			map[string]interface{}{
				"kind":    "MyKind",
				"group":   "example.com",
				"version": "v1",
				"source":  "api/v1/types.go:10",
			},
		},
	}
	result := RenderComponentMarkdown(data)
	if !strings.Contains(result, "github.com/org/repo/blob/abc123/api/v1/types.go#L10") {
		t.Error("missing source link in CRDs table")
	}
}

func TestRenderComponentMarkdown_NewSections(t *testing.T) {
	data := map[string]interface{}{
		"component": "full-component",
		"repo":      "org/full",
		"component_refs": []interface{}{
			map[string]interface{}{"target": "vllm", "type": "provider", "source": "providers/vllm/", "evidence": "directory: providers/vllm/"},
		},
		"operator_config": []interface{}{
			map[string]interface{}{"name": "IMG_KSERVE", "value": "quay.io/kserve:latest", "category": "image", "source": "pkg/constants.go:10"},
		},
		"api_types": []interface{}{
			map[string]interface{}{"name": "InferenceServiceSpec", "kind": "InferenceService", "fields_count": float64(12), "is_spec": true, "source": "api/v1/types.go:5"},
		},
		"reconcile_sequences": []interface{}{
			map[string]interface{}{
				"controller": "InferenceServiceReconciler",
				"steps": []interface{}{
					map[string]interface{}{"method": "reconcileDeployment", "resource_kind": "Deployment"},
					map[string]interface{}{"method": "reconcileService", "resource_kind": "Service"},
				},
			},
		},
		"prometheus_metrics": []interface{}{
			map[string]interface{}{"name": "inference_request_total", "type": "counter", "help": "Total inference requests"},
		},
		"status_conditions": []interface{}{
			map[string]interface{}{"type": "Ready", "reason": "MinimumReplicasAvailable"},
		},
		"feature_gates": []interface{}{
			map[string]interface{}{"name": "RawDeployment", "default": "false", "stage": "Alpha", "source": "pkg/features.go:1"},
		},
		"serving_runtimes": []interface{}{
			map[string]interface{}{"name": "kserve-triton", "protocol": "v2"},
		},
		"serving_runtime_refs": []interface{}{
			map[string]interface{}{"runtime": "triton", "crd_kind": "InferenceService", "source": "pkg/controller.go:1"},
		},
		"label_contracts": []interface{}{
			map[string]interface{}{"key": "app.kubernetes.io/part-of", "value": "kserve", "integration": "monitoring", "scope": "namespace"},
		},
		"kustomize_overlay_refs": []interface{}{
			map[string]interface{}{"overlay": "rhoai", "base": "config/default"},
		},
		"kustomize_components": []interface{}{
			map[string]interface{}{"name": "cert-manager", "path": "config/components/cert-manager"},
		},
		"configmap_volumes": []interface{}{
			map[string]interface{}{"configmap_name": "inference-config", "mount_path": "/etc/config", "deployment": "kserve-controller"},
		},
		"pod_disruption_budgets": []interface{}{
			map[string]interface{}{"name": "kserve-pdb", "min_available": "1"},
		},
		"horizontal_pod_autoscalers": []interface{}{
			map[string]interface{}{"name": "kserve-hpa", "min_replicas": float64(1), "max_replicas": float64(10)},
		},
		"python_k8s_calls": []interface{}{
			map[string]interface{}{"operation": "create", "resource_kind": "Pod", "source": "src/deploy.py:50"},
		},
		"template_files": []interface{}{
			map[string]interface{}{"path": "templates/deployment.yaml", "type": "go-template"},
		},
		"resource_defaults": []interface{}{
			map[string]interface{}{"resource": "kserve-controller", "cpu_request": "100m", "memory_request": "256Mi"},
		},
		"platform_detection": map[string]interface{}{
			"conditionals": []interface{}{
				map[string]interface{}{"check": "IsOpenShift", "type": "platform", "evidence": "pkg/platform.go:10"},
			},
		},
	}

	result := RenderComponentMarkdown(data)

	sections := []string{
		"## Component References", "## Operator Config", "## API Types",
		"## Reconciliation Sequences", "## Prometheus Metrics", "## Status Conditions",
		"## Feature Gates", "## Serving Runtimes", "## Serving Runtime References",
		"## Label Contracts", "## Kustomize Overlays", "## Kustomize Components",
		"## ConfigMap Volumes", "## Pod Disruption Budgets", "## Horizontal Pod Autoscalers",
		"## Python K8s API Calls", "## Template Files", "## Resource Defaults",
		"## Platform Detection",
	}
	for _, section := range sections {
		if !strings.Contains(result, section) {
			t.Errorf("missing section: %s", section)
		}
	}
	if !strings.Contains(result, "vllm") {
		t.Error("missing component ref target 'vllm'")
	}
	if !strings.Contains(result, "inference_request_total") {
		t.Error("missing prometheus metric name")
	}
	if !strings.Contains(result, "RawDeployment") {
		t.Error("missing feature gate name")
	}
}

func TestRenderComponentMarkdown_RoundTrip(t *testing.T) {
	// Build a data map with every possible field populated
	data := map[string]interface{}{
		"component":        "roundtrip-test",
		"repo":             "org/roundtrip",
		"commit_sha":       "abc123",
		"extracted_at":     "2026-05-08T00:00:00Z",
		"analyzer_version": "1.0.0",
		"aliases":          []interface{}{"rt-test"},
		"summary":          "A test component.",
		"crds":             []interface{}{map[string]interface{}{"kind": "X", "group": "g", "version": "v1", "source": "a.go:1"}},
		"webhooks":         []interface{}{map[string]interface{}{"name": "w1", "type": "validating"}},
		"http_endpoints":   []interface{}{map[string]interface{}{"method": "GET", "path": "/health"}},
		"services":         []interface{}{map[string]interface{}{"name": "svc", "type": "ClusterIP"}},
		"ingress_routing":  []interface{}{map[string]interface{}{"name": "ing1"}},
		"network_policies": []interface{}{map[string]interface{}{"name": "np1"}},
		"deployments":      []interface{}{map[string]interface{}{"name": "dep1", "containers": []interface{}{map[string]interface{}{"name": "c1", "image": "img"}}}},
		"rbac":             map[string]interface{}{"cluster_roles": []interface{}{map[string]interface{}{"name": "cr1", "rules": []interface{}{}}}},
		"secrets_referenced": []interface{}{map[string]interface{}{"name": "s1"}},
		"dependencies": map[string]interface{}{
			"internal_odh":    []interface{}{map[string]interface{}{"component": "other"}},
			"python_packages": []interface{}{map[string]interface{}{"name": "numpy"}},
		},
		"external_connections":       []interface{}{map[string]interface{}{"service": "s3"}},
		"runtime_dependencies":       []interface{}{map[string]interface{}{"name": "etcd"}},
		"controller_watches":         []interface{}{map[string]interface{}{"gvk": "apps/v1/Deployment", "type": "Owns"}},
		"configmaps":                 []interface{}{map[string]interface{}{"name": "cm1"}},
		"helm":                       map[string]interface{}{"charts": []interface{}{map[string]interface{}{"name": "mychart"}}},
		"dockerfiles":                []interface{}{map[string]interface{}{"path": "Dockerfile"}},
		"cache_config":               map[string]interface{}{"manager_type": "default"},
		"component_refs":             []interface{}{map[string]interface{}{"target": "vllm", "type": "provider"}},
		"operator_config":            []interface{}{map[string]interface{}{"name": "IMG", "value": "img:latest", "category": "image"}},
		"api_types":                  []interface{}{map[string]interface{}{"name": "Spec", "kind": "MyKind"}},
		"reconcile_sequences":        []interface{}{map[string]interface{}{"controller": "Ctrl", "steps": []interface{}{map[string]interface{}{"method": "reconcile"}}}},
		"prometheus_metrics":         []interface{}{map[string]interface{}{"name": "req_total", "type": "counter"}},
		"status_conditions":          []interface{}{map[string]interface{}{"type": "Ready"}},
		"feature_gates":              []interface{}{map[string]interface{}{"name": "Gate1"}},
		"serving_runtimes":           []interface{}{map[string]interface{}{"name": "rt1"}},
		"serving_runtime_refs":       []interface{}{map[string]interface{}{"runtime": "rt1", "crd_kind": "ISvc"}},
		"label_contracts":            []interface{}{map[string]interface{}{"key": "k", "value": "v"}},
		"kustomize_overlay_refs":     []interface{}{map[string]interface{}{"overlay": "rhoai"}},
		"kustomize_components":       []interface{}{map[string]interface{}{"name": "cert-mgr"}},
		"configmap_volumes":          []interface{}{map[string]interface{}{"configmap_name": "cm1"}},
		"pod_disruption_budgets":     []interface{}{map[string]interface{}{"name": "pdb1"}},
		"horizontal_pod_autoscalers": []interface{}{map[string]interface{}{"name": "hpa1"}},
		"python_k8s_calls":          []interface{}{map[string]interface{}{"operation": "create"}},
		"template_files":            []interface{}{map[string]interface{}{"path": "tmpl.yaml"}},
		"resource_defaults":         []interface{}{map[string]interface{}{"resource": "ctrl"}},
		"platform_detection":        map[string]interface{}{"conditionals": []interface{}{map[string]interface{}{"check": "IsOCP"}}},
		"data_coverage":             map[string]interface{}{"status": "full"},
	}

	result := RenderComponentMarkdown(data)

	expectedSections := []string{
		"## Metadata", "## CRDs", "## Webhooks", "## HTTP Endpoints",
		"## Services", "## Ingress Routing", "## Network Policies",
		"## Deployments", "## RBAC", "## Secrets Referenced",
		"## Dependencies", "## Controller Watches", "## ConfigMaps",
		"## Helm", "## Dockerfiles", "## Cache Architecture",
		"## Component References", "## Operator Config", "## API Types",
		"## Reconciliation Sequences", "## Prometheus Metrics",
		"## Status Conditions", "## Feature Gates", "## Serving Runtimes",
		"## Serving Runtime References", "## Label Contracts",
		"## Kustomize Overlays", "## Kustomize Components",
		"## ConfigMap Volumes", "## Pod Disruption Budgets",
		"## Horizontal Pod Autoscalers", "## Python K8s API Calls",
		"## Template Files", "## Resource Defaults", "## Platform Detection",
	}

	for _, section := range expectedSections {
		if !strings.Contains(result, section) {
			t.Errorf("round-trip validation failed: missing section %q", section)
		}
	}
}
