package renderer

import (
	"fmt"
	"sort"
	"strings"
)

// chartItem holds a label-value pair for bar chart rendering.
type chartItem struct {
	name  string
	value int
}

// renderHTMLBarChart generates an HTML horizontal bar chart with full component names.
// Uses inline styles so it renders in any markdown processor with md_in_html support.
func renderHTMLBarChart(b *strings.Builder, title string, items []chartItem, maxVal int) {
	if maxVal == 0 {
		maxVal = 1
	}
	b.WriteString(fmt.Sprintf("<div markdown class=\"bar-chart-container\" style=\"margin: 1em 0; padding: 1em; border: 1px solid var(--md-default-fg-color--lightest); border-radius: 8px;\">\n\n"))
	b.WriteString(fmt.Sprintf("**%s**\n\n", title))
	b.WriteString("<div style=\"display: flex; flex-direction: column; gap: 6px;\">\n")
	for _, item := range items {
		pct := item.value * 100 / maxVal
		if pct < 2 {
			pct = 2
		}
		// Color based on value thresholds
		color := "#27ae60" // green
		if item.value > 30 {
			color = "#e74c3c" // red
		} else if item.value > 10 {
			color = "#f39c12" // orange
		}
		b.WriteString(fmt.Sprintf("<div style=\"display: flex; align-items: center; gap: 8px;\">\n", ))
		b.WriteString(fmt.Sprintf("  <span style=\"min-width: 220px; text-align: right; font-size: 0.85em; white-space: nowrap;\">%s</span>\n", item.name))
		b.WriteString(fmt.Sprintf("  <div style=\"flex: 1; background: var(--md-default-fg-color--lightest); border-radius: 4px; height: 22px; position: relative;\">\n"))
		b.WriteString(fmt.Sprintf("    <div style=\"width: %d%%; background: %s; height: 100%%; border-radius: 4px; min-width: 20px;\"></div>\n", pct, color))
		b.WriteString(fmt.Sprintf("  </div>\n"))
		b.WriteString(fmt.Sprintf("  <span style=\"min-width: 30px; font-size: 0.85em; font-weight: 600;\">%d</span>\n", item.value))
		b.WriteString("</div>\n")
	}
	b.WriteString("</div>\n")
	b.WriteString("</div>\n\n")
}

// renderPlatformDocs generates a complete docs site from aggregated platform data.
func renderPlatformDocs(data map[string]interface{}) []DocsPage {
	var pages []DocsPage

	pages = append(pages, DocsPage{
		Path:    "index.md",
		Content: renderPlatformIndexDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "platform-architecture.md",
		Content: renderPlatformArchDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "network-topology.md",
		Content: renderPlatformNetworkDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "rbac-surface.md",
		Content: renderPlatformRBACDocPage(data),
	})
	pages = append(pages, DocsPage{
		Path:    "secrets-inventory.md",
		Content: renderPlatformSecretsDocPage(data),
	})

	// Per-component deep dive pages (dedup by component name)
	componentDataList := getSlice(data, "component_data")
	seenComps := make(map[string]bool)
	for _, compData := range componentDataList {
		compName := getStr(compData, "component", "")
		if compName == "" || seenComps[compName] {
			continue
		}
		seenComps[compName] = true
		compPages := renderComponentDocs(compData, "components/"+sanitizeID(compName))
		pages = append(pages, compPages...)
	}

	return pages
}

// --- Platform index page ---

func renderPlatformIndexDocPage(data map[string]interface{}) string {
	var b strings.Builder

	platformName := getStr(data, "platform", "Platform")
	components := getStringSlice(data, "components")
	crds := getSlice(data, "crds")
	services := getSlice(data, "services")
	secrets := getSlice(data, "secrets_referenced")
	rbacRoles := getSlice(data, "rbac_cluster_roles")
	depGraph := getSlice(data, "dependency_graph")

	b.WriteString(fmt.Sprintf("# %s Platform Analysis\n\n", platformName))
	b.WriteString("*Generated by rhoai-architecture-analyzer. All data produced by deterministic static analysis.*\n\n")

	// Summary
	b.WriteString("## Platform Summary\n\n")
	b.WriteString("| Metric | Count |\n")
	b.WriteString("|--------|-------|\n")
	b.WriteString(fmt.Sprintf("| Components | %d |\n", len(components)))
	b.WriteString(fmt.Sprintf("| CRDs | %d |\n", len(crds)))
	b.WriteString(fmt.Sprintf("| Services | %d |\n", len(services)))
	b.WriteString(fmt.Sprintf("| Secrets | %d |\n", len(secrets)))
	b.WriteString(fmt.Sprintf("| Cluster Roles | %d |\n", len(rbacRoles)))
	b.WriteString(fmt.Sprintf("| Cross-Component Dependencies | %d |\n", len(depGraph)))
	b.WriteString("\n")

	// Component dependency graph
	b.WriteString("## Component Dependency Graph\n\n")
	b.WriteString(renderPlatformDepGraphMermaid(data))
	b.WriteString("\n")

	// Component list
	b.WriteString("## Components Analyzed\n\n")
	if len(components) > 0 {
		sorted := make([]string, len(components))
		copy(sorted, components)
		sort.Strings(sorted)

		// Count CRDs per component
		crdCounts := make(map[string]int)
		for _, crd := range crds {
			owner := getStr(crd, "owner", "")
			crdCounts[owner]++
		}

		b.WriteString("| Component | CRDs |\n")
		b.WriteString("|-----------|------|\n")
		for _, comp := range sorted {
			count := crdCounts[comp]
			b.WriteString(fmt.Sprintf("| %s | %d |\n", comp, count))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// renderPlatformDepGraphMermaid builds a clean dependency graph showing only connected components.
// Multi-edges between the same pair are collapsed into a single edge with a summary label.
func renderPlatformDepGraphMermaid(data map[string]interface{}) string {
	var b strings.Builder

	components := getStringSlice(data, "components")
	depGraph := getSlice(data, "dependency_graph")
	componentSet := make(map[string]bool)
	for _, c := range components {
		componentSet[c] = true
	}

	// Collapse edges: group by from|to pair, collect types
	type edgePair struct{ from, to string }
	edgeTypes := make(map[edgePair][]string)
	edgeOrder := make([]edgePair, 0)
	for _, dep := range depGraph {
		from := getStr(dep, "from", "")
		to := getStr(dep, "to", "")
		depType := getStr(dep, "type", "")
		if from == "" || to == "" || from == to {
			continue
		}
		pair := edgePair{from, to}
		if _, exists := edgeTypes[pair]; !exists {
			edgeOrder = append(edgeOrder, pair)
		}
		edgeTypes[pair] = append(edgeTypes[pair], depType)
	}

	if len(edgeTypes) == 0 {
		return ""
	}

	// Collect only nodes that participate in at least one edge
	connectedNodes := make(map[string]bool)
	for pair := range edgeTypes {
		connectedNodes[pair.from] = true
		connectedNodes[pair.to] = true
	}

	crdCounts := make(map[string]int)
	for _, crd := range getSlice(data, "crds") {
		owner := getStr(crd, "owner", "")
		crdCounts[owner]++
	}

	b.WriteString("```mermaid\n")
	b.WriteString("%%{init: {'theme': 'base', 'flowchart': {'nodeSpacing': 30, 'rankSpacing': 50}}}%%\n")
	b.WriteString("graph LR\n")
	b.WriteString("    classDef internal fill:#3498db,stroke:#2980b9,color:#fff\n")
	b.WriteString("    classDef external fill:#95a5a6,stroke:#7f8c8d,color:#fff\n\n")

	// Emit connected nodes only
	emitted := make(map[string]bool)
	sortedNodes := make([]string, 0, len(connectedNodes))
	for n := range connectedNodes {
		sortedNodes = append(sortedNodes, n)
	}
	sort.Strings(sortedNodes)

	for _, comp := range sortedNodes {
		cid := sanitizeID(comp)
		if emitted[cid] {
			continue
		}
		emitted[cid] = true
		label := escapeLabel(comp)
		cls := "internal"
		if !componentSet[comp] {
			cls = "external"
		} else if crdCounts[comp] > 0 {
			label += fmt.Sprintf("\\n%d CRDs", crdCounts[comp])
		}
		b.WriteString(fmt.Sprintf("    %s[\"%s\"]:::%s\n", cid, label, cls))
	}
	b.WriteString("\n")

	// Emit collapsed edges
	for _, pair := range edgeOrder {
		types := edgeTypes[pair]
		fromID := sanitizeID(pair.from)
		toID := sanitizeID(pair.to)

		// Count watches, go-module, and uses-image separately
		watches := make([]string, 0)
		hasGoMod := false
		hasUsesImage := false
		other := make([]string, 0)
		for _, t := range types {
			if strings.HasPrefix(t, "watches-crd:") {
				watches = append(watches, t[len("watches-crd:"):])
			} else if t == "go-module" {
				hasGoMod = true
			} else if t == "uses-image" {
				hasUsesImage = true
			} else {
				other = append(other, t)
			}
		}

		if hasGoMod {
			b.WriteString(fmt.Sprintf("    %s -.->|\"go-module\"| %s\n", fromID, toID))
		}
		if hasUsesImage {
			b.WriteString(fmt.Sprintf("    %s -->|\"sidecar\"| %s\n", fromID, toID))
		}
		if len(watches) > 0 {
			label := fmt.Sprintf("watches %d CRDs", len(watches))
			if len(watches) <= 2 {
				label = "watches " + strings.Join(watches, ", ")
			}
			b.WriteString(fmt.Sprintf("    %s ==>|\"%s\"| %s\n", fromID, escapeLabel(label), toID))
		}
		for _, t := range other {
			b.WriteString(fmt.Sprintf("    %s -->|\"%s\"| %s\n", fromID, escapeLabel(t), toID))
		}
	}

	b.WriteString("```\n")
	return b.String()
}

// --- Platform architecture page ---

func renderPlatformArchDocPage(data map[string]interface{}) string {
	var b strings.Builder

	b.WriteString("# Platform Architecture\n\n")

	// CRD Ownership Map: derive from crds array (not crd_ownership which is lossy)
	crds := getSlice(data, "crds")

	b.WriteString("## CRD Ownership Map\n\n")
	b.WriteString(fmt.Sprintf("The platform defines %d CRDs. Each CRD is owned by the component that declares it.\n\n", len(crds)))

	if len(crds) > 0 {
		// Group CRDs by owner from the crds array directly
		ownerCRDs := make(map[string][]string)
		seen := make(map[string]bool)
		for _, crd := range crds {
			owner := getStr(crd, "owner", "")
			kind := getStr(crd, "kind", "")
			if owner == "" || kind == "" {
				continue
			}
			key := owner + "|" + kind
			if seen[key] {
				continue
			}
			seen[key] = true
			ownerCRDs[owner] = append(ownerCRDs[owner], kind)
		}

		owners := make([]string, 0, len(ownerCRDs))
		for o := range ownerCRDs {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		b.WriteString("| Owner | CRDs | Count |\n")
		b.WriteString("|-------|------|-------|\n")
		for _, owner := range owners {
			kinds := ownerCRDs[owner]
			sort.Strings(kinds)
			b.WriteString(fmt.Sprintf("| **%s** | %s | %d |\n", owner, strings.Join(kinds, ", "), len(kinds)))
		}
		b.WriteString("\n")
	}

	// Cross-component dependencies
	depGraph := getSlice(data, "dependency_graph")
	b.WriteString("## Cross-Component Dependencies\n\n")
	if len(depGraph) > 0 {
		b.WriteString("Relationships detected through Go module imports and CRD watch patterns.\n\n")
		b.WriteString("| From | To | Type |\n")
		b.WriteString("|------|----|------|\n")
		for _, dep := range depGraph {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				getStr(dep, "from", ""), getStr(dep, "to", ""),
				getStr(dep, "type", "")))
		}
		b.WriteString("\n")

		// Find tightest coupling
		couplingCounts := make(map[string]int)
		for _, dep := range depGraph {
			from := getStr(dep, "from", "")
			to := getStr(dep, "to", "")
			if from != to {
				key := from + " -> " + to
				couplingCounts[key]++
			}
		}
		maxKey, maxCount := "", 0
		for k, v := range couplingCounts {
			if v > maxCount || (v == maxCount && k < maxKey) {
				maxKey, maxCount = k, v
			}
		}
		if maxCount > 1 {
			b.WriteString(fmt.Sprintf("**Tightest coupling:** `%s` (%d dependency edges).\n\n", maxKey, maxCount))
		}
	} else {
		b.WriteString("No cross-component dependencies detected.\n\n")
	}

	return b.String()
}

// --- Platform network page ---

func renderPlatformNetworkDocPage(data map[string]interface{}) string {
	var b strings.Builder

	services := getSlice(data, "services")
	b.WriteString("# Network Topology\n\n")
	b.WriteString(fmt.Sprintf("%d Kubernetes services across the platform.\n\n", len(services)))

	// Kiali-style network topology graph
	renderPlatformNetworkTopologyGraph(&b, data)

	if len(services) > 0 {
		// Group services by owner
		ownerServices := make(map[string][]map[string]interface{})
		for _, svc := range services {
			owner := getStr(svc, "owner", "unknown")
			ownerServices[owner] = append(ownerServices[owner], svc)
		}

		owners := make([]string, 0, len(ownerServices))
		for o := range ownerServices {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		// Detect cross-component service references (same service name in multiple components)
		type svcRef struct {
			owner   string
			service string
		}
		svcNameRefs := make(map[string][]svcRef)
		for _, owner := range owners {
			for _, svc := range ownerServices[owner] {
				name := getStr(svc, "name", "")
				svcNameRefs[name] = append(svcNameRefs[name], svcRef{owner, name})
			}
		}

		// Filter to real cross-component refs
		type crossRef struct {
			from    string
			to      string
			service string
		}
		var crossRefs []crossRef
		for name, refs := range svcNameRefs {
			if len(refs) < 2 {
				continue
			}
			lower := strings.ToLower(name)
			isGeneric := lower == "service" ||
				strings.Contains(lower, "webhook") ||
				strings.Contains(lower, "proxy") ||
				strings.Contains(lower, "metrics") ||
				strings.Contains(lower, "health") ||
				lower == "grpc" || lower == "api"
			if isGeneric {
				continue
			}
			sort.Slice(refs, func(i, j int) bool { return refs[i].owner < refs[j].owner })
			primary := refs[0]
			for _, ref := range refs[1:] {
				crossRefs = append(crossRefs, crossRef{ref.owner, primary.owner, name})
			}
		}

		// Cross-component service graph (only if there are cross-refs)
		if len(crossRefs) > 0 {
			b.WriteString("## Cross-Component Service References\n\n")
			b.WriteString("Services referenced across component boundaries. When component A defines a service that component B also references, it indicates a deployment dependency.\n\n")
			b.WriteString("```mermaid\n")
			b.WriteString("graph LR\n")
			b.WriteString("    classDef comp fill:#3498db,stroke:#2980b9,color:#fff\n\n")

			// Emit only the connected components
			connectedComps := make(map[string]bool)
			for _, cr := range crossRefs {
				connectedComps[cr.from] = true
				connectedComps[cr.to] = true
			}
			sortedComps := make([]string, 0, len(connectedComps))
			for c := range connectedComps {
				sortedComps = append(sortedComps, c)
			}
			sort.Strings(sortedComps)
			for _, comp := range sortedComps {
				b.WriteString(fmt.Sprintf("    %s[\"%s\"]:::comp\n", sanitizeID(comp), escapeLabel(comp)))
			}
			b.WriteString("\n")
			for _, cr := range crossRefs {
				b.WriteString(fmt.Sprintf("    %s -.->|\"%s\"| %s\n",
					sanitizeID(cr.from), escapeLabel(cr.service), sanitizeID(cr.to)))
			}
			b.WriteString("```\n\n")
		}

		// Services summary table
		b.WriteString("## Services by Component\n\n")
		b.WriteString(fmt.Sprintf("| Component | Services | Webhook (443) | Metrics (8443) | Data |\n"))
		b.WriteString("|-----------|----------|---------------|----------------|------|\n")
		for _, owner := range owners {
			svcs := ownerServices[owner]
			webhookCount, metricsCount, dataCount := 0, 0, 0
			for _, svc := range svcs {
				ports := getSlice(svc, "ports")
				classified := false
				for _, p := range ports {
					port := getInt(p, "port")
					if port == 443 {
						webhookCount++
						classified = true
					} else if port == 8443 {
						metricsCount++
						classified = true
					}
				}
				if !classified {
					dataCount++
				}
			}
			b.WriteString(fmt.Sprintf("| %s | %d | %d | %d | %d |\n",
				owner, len(svcs), webhookCount, metricsCount, dataCount))
		}
		b.WriteString("\n")

		// Full service detail: grouped by component, no Owner column duplication
		b.WriteString("## Service Detail\n\n")
		b.WriteString("Per-component service breakdown with exact port numbers and protocols.\n\n")
		for _, owner := range owners {
			svcs := ownerServices[owner]
			b.WriteString(fmt.Sprintf("### %s (%d services)\n\n", owner, len(svcs)))
			b.WriteString("| Service | Type | Ports |\n")
			b.WriteString("|---------|------|-------|\n")
			for _, svc := range svcs {
				ports := getSlice(svc, "ports")
				var portParts []string
				for _, p := range ports {
					portParts = append(portParts, fmt.Sprintf("%d/%s",
						getInt(p, "port"), getStr(p, "protocol", "TCP")))
				}
				b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
					getStr(svc, "name", ""),
					getStr(svc, "type", "ClusterIP"),
					strings.Join(portParts, ", ")))
			}
			b.WriteString("\n")
		}

		// Port patterns
		b.WriteString("## Port Patterns\n\n")
		portGroups := make(map[string][]string)
		for _, svc := range services {
			ports := getSlice(svc, "ports")
			for _, p := range ports {
				port := fmt.Sprintf("%d/TCP", getInt(p, "port"))
				name := getStr(svc, "name", "")
				portGroups[port] = append(portGroups[port], name)
			}
		}
		portKeys := make([]string, 0, len(portGroups))
		for k := range portGroups {
			portKeys = append(portKeys, k)
		}
		sort.Strings(portKeys)
		for _, port := range portKeys {
			svcs := portGroups[port]
			b.WriteString(fmt.Sprintf("- **%s**: %s\n", port, strings.Join(svcs, ", ")))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// --- Platform RBAC page ---

func renderPlatformRBACDocPage(data map[string]interface{}) string {
	var b strings.Builder

	rbacRoles := getSlice(data, "rbac_cluster_roles")
	b.WriteString("# RBAC Surface\n\n")
	b.WriteString(fmt.Sprintf("%d cluster roles across the platform.\n\n", len(rbacRoles)))

	if len(rbacRoles) > 0 {
		// Permission scope summary: one bar per component showing role count and max breadth
		ownerRoles := make(map[string][]RoleSummary)
		for _, role := range rbacRoles {
			owner := getStr(role, "owner", "")
			ownerRoles[owner] = append(ownerRoles[owner], computeRoleSummary(role, "ClusterRole"))
		}

		owners := make([]string, 0, len(ownerRoles))
		for o := range ownerRoles {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		b.WriteString("## Permission Scope by Component\n\n")
		b.WriteString("How many distinct Kubernetes resource types can each component's most powerful ClusterRole access? ")
		b.WriteString("A wider scope means the component can read/write more types of resources, which increases its blast radius if compromised. ")
		b.WriteString("Color: \U0001F534 wide (>30 types), \U0001F7E0 medium (10-30), \U0001F7E2 narrow (<10).\n\n")

		var chartItems []chartItem
		maxVal := 0
		for _, owner := range owners {
			roles := ownerRoles[owner]
			maxRes := 0
			for _, r := range roles {
				if r.ResourceCount > maxRes {
					maxRes = r.ResourceCount
				}
			}
			chartItems = append(chartItems, chartItem{owner, maxRes})
			if maxRes > maxVal {
				maxVal = maxRes
			}
		}
		renderHTMLBarChart(&b, "Widest Role Scope (resource types)", chartItems, maxVal)

		// RBAC graph: ServiceAccount -> Role bindings across the platform
		b.WriteString("## RBAC Binding Graph\n\n")
		b.WriteString("Subject-to-role bindings across all platform components. Edge direction shows who has access to what.\n\n")
		rbacRoles := getSlice(data, "rbac_cluster_roles")
		componentData := getSlice(data, "component_data")
		renderPlatformRBACGraph(&b, rbacRoles, componentData)

		// Roles by component, no duplicate detail table
		b.WriteString("## Roles by Component\n\n")
		b.WriteString("| Component | Roles | Widest Role | Resources | Scope |\n")
		b.WriteString("|-----------|-------|-------------|-----------|-------|\n")
		for _, owner := range owners {
			roles := ownerRoles[owner]
			sort.Slice(roles, func(i, j int) bool {
				return roles[i].ResourceCount > roles[j].ResourceCount
			})
			widest := roles[0]
			scope := "narrow"
			if widest.ResourceCount > 30 {
				scope = "**wide**"
			} else if widest.ResourceCount > 10 {
				scope = "medium"
			}
			b.WriteString(fmt.Sprintf("| %s | %d | %s | %d | %s |\n",
				owner, len(roles), widest.Name, widest.ResourceCount, scope))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// --- Platform secrets page ---

func renderPlatformSecretsDocPage(data map[string]interface{}) string {
	var b strings.Builder

	secrets := getSlice(data, "secrets_referenced")
	b.WriteString("# Secrets Inventory\n\n")
	b.WriteString(fmt.Sprintf("%d secrets referenced across the platform. No secret values are extracted, only names, types, and which component references them.\n\n", len(secrets)))

	if len(secrets) > 0 {
		// Group by owner
		ownerSecrets := make(map[string][]map[string]interface{})
		for _, s := range secrets {
			owner := getStr(s, "owner", "unknown")
			ownerSecrets[owner] = append(ownerSecrets[owner], s)
		}

		owners := make([]string, 0, len(ownerSecrets))
		for o := range ownerSecrets {
			owners = append(owners, o)
		}
		sort.Strings(owners)

		// Bar chart: secrets per component
		b.WriteString("## Secret Distribution\n\n")
		var secretItems []chartItem
		secretMax := 0
		for _, owner := range owners {
			count := len(ownerSecrets[owner])
			secretItems = append(secretItems, chartItem{owner, count})
			if count > secretMax {
				secretMax = count
			}
		}
		renderHTMLBarChart(&b, "Secrets per Component", secretItems, secretMax)

		// Summary table
		b.WriteString("## Secrets by Component\n\n")
		b.WriteString("| Component | TLS | Opaque | Total |\n")
		b.WriteString("|-----------|-----|--------|-------|\n")
		for _, owner := range owners {
			tlsCount := 0
			opaqueCount := 0
			for _, s := range ownerSecrets[owner] {
				stype := getStr(s, "type", "Opaque")
				if strings.Contains(stype, "tls") {
					tlsCount++
				} else {
					opaqueCount++
				}
			}
			b.WriteString(fmt.Sprintf("| %s | %d | %d | %d |\n",
				owner, tlsCount, opaqueCount, tlsCount+opaqueCount))
		}
		b.WriteString("\n")

		// Per-component secret detail (grouped, not duplicating summary columns)
		b.WriteString("## Secret Detail\n\n")
		b.WriteString("Per-component secret breakdown by name and type.\n\n")
		for _, owner := range owners {
			secrets := ownerSecrets[owner]
			b.WriteString(fmt.Sprintf("### %s (%d secrets)\n\n", owner, len(secrets)))
			b.WriteString("| Secret | Type |\n")
			b.WriteString("|--------|------|\n")
			for _, s := range secrets {
				b.WriteString(fmt.Sprintf("| %s | %s |\n",
					getStr(s, "name", ""), getStr(s, "type", "Opaque")))
			}
			b.WriteString("\n")
		}

		// Patterns
		b.WriteString("## Patterns\n\n")
		webhookCount := 0
		tlsCount := 0
		for _, s := range secrets {
			name := getStr(s, "name", "")
			stype := getStr(s, "type", "")
			if strings.Contains(name, "webhook") || strings.Contains(name, "cert") {
				webhookCount++
			}
			if strings.Contains(stype, "tls") {
				tlsCount++
			}
		}
		if webhookCount > 0 {
			b.WriteString(fmt.Sprintf("- **Webhook certs** are the dominant secret type (%d of %d secrets).\n", webhookCount, len(secrets)))
		}
		if tlsCount > 0 {
			b.WriteString(fmt.Sprintf("- **kubernetes.io/tls** secrets (%d) are used for TLS-terminated services.\n", tlsCount))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// renderPlatformRBACGraph generates a Mermaid graph showing ServiceAccount -> Role bindings.
func renderPlatformRBACGraph(b *strings.Builder, rbacRoles []map[string]interface{}, componentData []map[string]interface{}) {
	type binding struct {
		subject  string
		subjKind string
		role     string
		owner    string
	}
	var bindings []binding
	for _, comp := range componentData {
		owner := getStr(comp, "component", "")
		rbac := getMap(comp, "rbac")
		if rbac == nil {
			continue
		}
		for _, bd := range getSlice(rbac, "cluster_role_bindings") {
			roleRef := getStr(bd, "role_ref", "")
			for _, subj := range getSlice(bd, "subjects") {
				bindings = append(bindings, binding{
					subject:  getStr(subj, "name", ""),
					subjKind: getStr(subj, "kind", ""),
					role:     roleRef,
					owner:    owner,
				})
			}
		}
	}

	if len(bindings) == 0 {
		b.WriteString("No RBAC bindings found across components.\n\n")
		return
	}

	if len(bindings) > 50 {
		b.WriteString(fmt.Sprintf("*%d bindings total. Showing the first 50.*\n\n", len(bindings)))
		bindings = bindings[:50]
	}

	b.WriteString("```mermaid\n")
	b.WriteString("graph LR\n")
	b.WriteString("    classDef role fill:#e74c3c,stroke:#c0392b,color:#fff\n")
	b.WriteString("    classDef subject fill:#3498db,stroke:#2980b9,color:#fff\n\n")

	emittedNodes := make(map[string]bool)
	for _, bind := range bindings {
		subjID := sanitizeID("sa_" + bind.subject)
		roleID := sanitizeID("role_" + bind.role)
		if !emittedNodes[subjID] {
			emittedNodes[subjID] = true
			b.WriteString(fmt.Sprintf("    %s[\"%s\\n%s\"]:::subject\n",
				subjID, escapeLabel(bind.subject), bind.subjKind))
		}
		if !emittedNodes[roleID] {
			emittedNodes[roleID] = true
			b.WriteString(fmt.Sprintf("    %s[\"%s\"]:::role\n",
				roleID, escapeLabel(bind.role)))
		}
		b.WriteString(fmt.Sprintf("    %s -->|%s| %s\n", subjID, escapeLabel(bind.owner), roleID))
	}

	b.WriteString("```\n\n")
}

// renderPlatformNetworkTopologyGraph generates a Kiali-style network topology
// showing components, their services, external dependencies, and traffic flows.
func renderPlatformNetworkTopologyGraph(b *strings.Builder, data map[string]interface{}) {
	componentData := getSlice(data, "component_data")
	if len(componentData) == 0 {
		return
	}

	b.WriteString("## Network Topology Graph\n\n")
	b.WriteString("Service mesh view of the platform. Components are grouped with their services. ")
	b.WriteString("Arrows show inter-component dependencies (CRD watches, Go module imports, sidecar injection) and external service connections.\n\n")

	b.WriteString("```mermaid\n")
	b.WriteString("%%{init: {'theme': 'base', 'flowchart': {'nodeSpacing': 20, 'rankSpacing': 40, 'curve': 'basis'}}}%%\n")
	b.WriteString("graph TB\n")
	b.WriteString("    classDef comp fill:#3498db,stroke:#2980b9,color:#fff\n")
	b.WriteString("    classDef svc fill:#2ecc71,stroke:#27ae60,color:#fff,font-size:10px\n")
	b.WriteString("    classDef ext fill:#e74c3c,stroke:#c0392b,color:#fff\n")
	b.WriteString("    classDef netpol fill:#f39c12,stroke:#d68910,color:#fff,font-size:10px\n")
	b.WriteString("    classDef webhook fill:#9b59b6,stroke:#8e44ad,color:#fff,font-size:10px\n\n")

	// Collect per-component data
	type compInfo struct {
		name       string
		services   []map[string]interface{}
		extConns   []map[string]interface{}
		webhooks   []map[string]interface{}
		netPols    []map[string]interface{}
		hasIngress bool
	}

	var components []compInfo
	for _, cd := range componentData {
		name := getStr(cd, "component", "")
		if name == "" {
			continue
		}
		ci := compInfo{
			name:     name,
			services: getSlice(cd, "services"),
			extConns: getSlice(cd, "external_connections"),
			webhooks: getSlice(cd, "webhooks"),
			netPols:  getSlice(cd, "network_policies"),
		}
		ci.hasIngress = len(getSlice(cd, "ingress_routing")) > 0
		components = append(components, ci)
	}

	// Sort by name for stable output
	sort.Slice(components, func(i, j int) bool {
		return components[i].name < components[j].name
	})

	// Render each component as a subgraph with its services
	for _, comp := range components {
		compID := sanitizeID(comp.name)

		// Dedup services by name
		type svcKey struct{ name, svcType string }
		seen := make(map[svcKey]bool)
		var uniqueSvcs []map[string]interface{}
		for _, svc := range comp.services {
			key := svcKey{getStr(svc, "name", ""), getStr(svc, "type", "")}
			source := getStr(svc, "source", "")
			isTest := strings.Contains(source, "/test/") || strings.Contains(source, "/e2e/") || strings.Contains(source, "/testdata/")
			if !seen[key] && !isTest {
				seen[key] = true
				uniqueSvcs = append(uniqueSvcs, svc)
			}
		}

		if len(uniqueSvcs) > 0 || len(comp.extConns) > 0 {
			b.WriteString(fmt.Sprintf("    subgraph %s_sub[\"%s\"]\n", compID, escapeLabel(comp.name)))
			b.WriteString(fmt.Sprintf("        %s([\"%s\"]):::%s\n", compID, escapeLabel(comp.name), "comp"))

			// Services (limit to 5 per component to keep graph readable)
			displaySvcs := uniqueSvcs
			if len(displaySvcs) > 5 {
				displaySvcs = displaySvcs[:5]
			}
			for i, svc := range displaySvcs {
				svcName := getStr(svc, "name", "")
				ports := getSlice(svc, "ports")
				var portStr string
				if len(ports) > 0 {
					portParts := make([]string, 0)
					for _, p := range ports {
						portParts = append(portParts, fmt.Sprintf("%d", getInt(p, "port")))
					}
					portStr = strings.Join(portParts, ",")
				}
				svcID := fmt.Sprintf("%s_svc_%d", compID, i)
				label := escapeLabel(svcName)
				if portStr != "" {
					label += "\\n:" + portStr
				}
				b.WriteString(fmt.Sprintf("        %s[\"%s\"]:::svc\n", svcID, label))
				b.WriteString(fmt.Sprintf("        %s --- %s\n", compID, svcID))
			}
			if len(uniqueSvcs) > 5 {
				moreID := fmt.Sprintf("%s_svc_more", compID)
				b.WriteString(fmt.Sprintf("        %s[\"+%d more\"]:::svc\n", moreID, len(uniqueSvcs)-5))
			}

			// Network policy indicator
			if len(comp.netPols) > 0 {
				npID := fmt.Sprintf("%s_np", compID)
				b.WriteString(fmt.Sprintf("        %s{{\"%d NetworkPolicies\"}}:::netpol\n", npID, len(comp.netPols)))
				b.WriteString(fmt.Sprintf("        %s -.- %s\n", npID, compID))
			}

			b.WriteString("    end\n")
		} else {
			// Component with no services
			b.WriteString(fmt.Sprintf("    %s([\"%s\"]):::%s\n", compID, escapeLabel(comp.name), "comp"))
		}
	}

	b.WriteString("\n")

	// External services (deduplicated)
	extSeen := make(map[string]bool)
	for _, comp := range components {
		for _, ec := range comp.extConns {
			service := getStr(ec, "service", "")
			ecType := getStr(ec, "type", "")
			key := ecType + "/" + service
			if !extSeen[key] && service != "" {
				extSeen[key] = true
				extID := sanitizeID("ext_" + service)
				b.WriteString(fmt.Sprintf("    %s[[\"%s\\n%s\"]]:::ext\n", extID, escapeLabel(service), ecType))
			}
		}
	}
	b.WriteString("\n")

	// Inter-component dependency edges
	depGraph := getSlice(data, "dependency_graph")
	type edgePair struct{ from, to string }
	edgeLabels := make(map[edgePair][]string)
	edgeOrder := make([]edgePair, 0)
	for _, dep := range depGraph {
		from := getStr(dep, "from", "")
		to := getStr(dep, "to", "")
		depType := getStr(dep, "type", "")
		if from == "" || to == "" || from == to {
			continue
		}
		pair := edgePair{from, to}
		if _, exists := edgeLabels[pair]; !exists {
			edgeOrder = append(edgeOrder, pair)
		}
		edgeLabels[pair] = append(edgeLabels[pair], depType)
	}

	for _, pair := range edgeOrder {
		fromID := sanitizeID(pair.from)
		toID := sanitizeID(pair.to)
		labels := edgeLabels[pair]

		// Classify edge type
		hasWatch := false
		hasSidecar := false
		for _, l := range labels {
			if strings.HasPrefix(l, "watches-crd") {
				hasWatch = true
			}
			if l == "uses-image" {
				hasSidecar = true
			}
		}

		if hasWatch {
			b.WriteString(fmt.Sprintf("    %s ==>|watches| %s\n", fromID, toID))
		} else if hasSidecar {
			b.WriteString(fmt.Sprintf("    %s -->|sidecar| %s\n", fromID, toID))
		} else {
			b.WriteString(fmt.Sprintf("    %s -.->|module| %s\n", fromID, toID))
		}
	}

	// External connection edges
	for _, comp := range components {
		compID := sanitizeID(comp.name)
		extConnSeen := make(map[string]bool)
		for _, ec := range comp.extConns {
			service := getStr(ec, "service", "")
			if service == "" || extConnSeen[service] {
				continue
			}
			extConnSeen[service] = true
			extID := sanitizeID("ext_" + service)
			b.WriteString(fmt.Sprintf("    %s -.-> %s\n", compID, extID))
		}
	}

	b.WriteString("```\n\n")
}
