package renderer

import (
	"fmt"
	"sort"
	"strings"
)

// renderPlatformReport generates a PLATFORM.md from aggregated data.
func renderPlatformReport(data map[string]interface{}) string {
	var b strings.Builder

	b.WriteString("# Platform Architecture\n\n")
	b.WriteString("*Generated by architecture-analyzer (deterministic static analysis)*\n\n")
	b.WriteString("---\n\n")

	// Platform Summary
	components := getStringSlice(data, "components")
	crds := getSlice(data, "crds")
	services := getSlice(data, "services")
	secrets := getSlice(data, "secrets_referenced")
	rbacRoles := getSlice(data, "rbac_cluster_roles")
	depGraph := getSlice(data, "dependency_graph")

	b.WriteString("## Platform Summary\n\n")
	b.WriteString(fmt.Sprintf("| Metric | Count |\n"))
	b.WriteString(fmt.Sprintf("|--------|-------|\n"))
	b.WriteString(fmt.Sprintf("| Components | %d |\n", len(components)))
	b.WriteString(fmt.Sprintf("| CRDs | %d |\n", len(crds)))
	b.WriteString(fmt.Sprintf("| Services | %d |\n", len(services)))
	b.WriteString(fmt.Sprintf("| Secrets | %d |\n", len(secrets)))
	b.WriteString(fmt.Sprintf("| Cluster Roles | %d |\n", len(rbacRoles)))
	b.WriteString(fmt.Sprintf("| Cross-Component Dependencies | %d |\n", len(depGraph)))
	b.WriteString("\n")

	// Component Registry
	b.WriteString("## Component Registry\n\n")
	if len(components) > 0 {
		sort.Strings(components)
		b.WriteString("| Component |\n")
		b.WriteString("|-----------|\n")
		for _, comp := range components {
			b.WriteString(fmt.Sprintf("| %s |\n", comp))
		}
		b.WriteString("\n")
	}

	// CRD Ownership Map
	b.WriteString("## CRD Ownership Map\n\n")
	crdOwnership := getMap(data, "crd_ownership")
	if crdOwnership != nil && len(crdOwnership) > 0 {
		// Sort by owner then kind
		type crdEntry struct {
			kind  string
			owner string
		}
		var entries []crdEntry
		for kind, owner := range crdOwnership {
			ownerStr, _ := owner.(string)
			entries = append(entries, crdEntry{kind: kind, owner: ownerStr})
		}
		sort.Slice(entries, func(i, j int) bool {
			if entries[i].owner != entries[j].owner {
				return entries[i].owner < entries[j].owner
			}
			return entries[i].kind < entries[j].kind
		})

		b.WriteString("| Owner | Kind |\n")
		b.WriteString("|-------|------|\n")
		for _, e := range entries {
			b.WriteString(fmt.Sprintf("| %s | %s |\n", e.owner, e.kind))
		}
		b.WriteString("\n")
	} else {
		b.WriteString("No CRDs found.\n\n")
	}

	// Cross-Component Dependencies
	b.WriteString("## Cross-Component Dependencies\n\n")
	if len(depGraph) > 0 {
		b.WriteString("| From | To | Type |\n")
		b.WriteString("|------|----|------|\n")
		for _, dep := range depGraph {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				getStr(dep, "from", ""), getStr(dep, "to", ""),
				getStr(dep, "type", "")))
		}
		b.WriteString("\n")
	} else {
		b.WriteString("No cross-component dependencies found.\n\n")
	}

	// Shared Secrets
	b.WriteString("## Secrets Referenced\n\n")
	if len(secrets) > 0 {
		b.WriteString("| Secret | Owner | Type |\n")
		b.WriteString("|--------|-------|------|\n")
		for _, s := range secrets {
			b.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
				getStr(s, "name", ""), getStr(s, "owner", ""),
				getStr(s, "type", "")))
		}
		b.WriteString("\n")
	}

	// RBAC Surface
	b.WriteString("## RBAC Surface\n\n")
	if len(rbacRoles) > 0 {
		b.WriteString("| Owner | Role | Resource Count |\n")
		b.WriteString("|-------|------|----------------|\n")
		for _, role := range rbacRoles {
			rs := computeRoleSummary(role, "ClusterRole")
			b.WriteString(fmt.Sprintf("| %s | %s | %d |\n",
				getStr(role, "owner", ""), rs.Name,
				rs.ResourceCount))
		}
		b.WriteString("\n")
	}

	// Network Topology
	b.WriteString("## Network Topology\n\n")
	if len(services) > 0 {
		b.WriteString("| Owner | Service | Type | Ports |\n")
		b.WriteString("|-------|---------|------|-------|\n")
		for _, svc := range services {
			ports := getSlice(svc, "ports")
			var portParts []string
			for _, p := range ports {
				portParts = append(portParts, fmt.Sprintf("%v/%s",
					p["port"], getStr(p, "protocol", "TCP")))
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				getStr(svc, "owner", ""), getStr(svc, "name", ""),
				getStr(svc, "type", "ClusterIP"),
				strings.Join(portParts, ", ")))
		}
		b.WriteString("\n")
	}

	return b.String()
}
