// Package report generates comprehensive markdown reports from
// architecture-analyzer component-architecture.json output.
package report

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateImageReport produces a comprehensive image and container analysis
// report from one or more component-architecture.json datasets.
func GenerateImageReport(components map[string]map[string]interface{}) string {
	var b strings.Builder

	totalDF := 0
	totalDep := 0
	totalContainers := 0
	for _, data := range components {
		totalDF += len(getSlice(data, "dockerfiles"))
		deps := getSlice(data, "deployments")
		totalDep += len(deps)
		for _, dep := range deps {
			totalContainers += len(getSlice(dep, "containers"))
		}
	}

	b.WriteString("# Component Image & Container Analysis\n\n")
	b.WriteString("> Auto-generated by [architecture-analyzer](https://github.com/ugiordan/architecture-analyzer)\n")
	b.WriteString("> from deterministic static analysis.\n\n")
	b.WriteString(fmt.Sprintf("**%d components** | **%d Dockerfiles** | **%d deployments** | **%d containers**\n\n", len(components), totalDF, totalDep, totalContainers))

	names := sortedKeys(components)

	writeGPUSection(&b, components, names)
	writeRegistrySection(&b, components)
	writeMultiArchSection(&b, components, names)
	writeDockerfileIssuesSection(&b, components, names)
	writeSecurityContextSection(&b, components, names)
	writeResourceLimitsSection(&b, components, names)
	writeHealthProbeSection(&b, components, names)
	writeSidecarSection(&b, components, names)
	writeDeploymentIssuesSection(&b, components)
	writeImageConstantsSection(&b, components, names)

	return b.String()
}

// GenerateSingleComponentReport produces a report for a single component.
func GenerateSingleComponentReport(data map[string]interface{}) string {
	name := getStr(data, "component", "unknown")
	return GenerateImageReport(map[string]map[string]interface{}{name: data})
}

func writeGPUSection(b *strings.Builder, components map[string]map[string]interface{}, names []string) {
	b.WriteString("## GPU / CUDA / Accelerator Dependencies\n\n")
	b.WriteString("| Component | Dockerfile | Base Image | CUDA Version | Accelerator | Notes |\n")
	b.WriteString("|-----------|-----------|------------|-------------|-------------|-------|\n")

	found := false
	for _, name := range names {
		for _, df := range getSlice(components[name], "dockerfiles") {
			baseImg := getStr(df, "base_image", "")
			path := getStr(df, "path", "")
			cudaVer, accel, notes := classifyGPU(baseImg, path)
			if accel == "" {
				continue
			}
			found = true
			for _, issue := range getStringSlice(df, "issues") {
				notes = append(notes, issue)
			}
			b.WriteString(fmt.Sprintf("| %s | `%s` | `%s` | %s | %s | %s |\n",
				name, path, truncate(baseImg, 55), cudaVer, accel, strings.Join(notes, "; ")))
		}
	}
	if !found {
		b.WriteString("| (none) | | | | | |\n")
	}
	b.WriteString("\n")
}

func classifyGPU(baseImg, path string) (cudaVer string, accel string, notes []string) {
	lower := strings.ToLower(baseImg)
	lowerPath := strings.ToLower(path)

	if strings.Contains(lower, "cuda") || strings.Contains(lower, "nvidia") || strings.Contains(lower, "nvcr.io") {
		accel = "NVIDIA CUDA"
		cudaVer = extractVersion(lower, lowerPath, "cuda")
	} else if strings.Contains(lowerPath, "cuda") {
		accel = "NVIDIA CUDA"
		cudaVer = extractVersion(lower, lowerPath, "cuda")
	} else if strings.Contains(lowerPath, "hpu") || strings.Contains(lower, "habana") {
		accel = "Intel Gaudi (HPU)"
	} else if strings.Contains(lowerPath, "rocm") || strings.Contains(lower, "rocm") {
		accel = "AMD ROCm"
		cudaVer = extractVersion(lower, lowerPath, "rocm")
	} else if strings.Contains(lower, "vllm") {
		accel = "GPU (vLLM)"
		notes = append(notes, "vLLM typically requires CUDA")
	}
	if cudaVer == "" {
		cudaVer = "-"
	}
	return
}

func extractVersion(imgLower, pathLower, prefix string) string {
	for _, s := range []string{imgLower, pathLower} {
		idx := strings.Index(s, prefix)
		if idx < 0 {
			continue
		}
		rest := s[idx+len(prefix):]
		rest = strings.TrimLeft(rest, ":-_")
		ver := ""
		for _, ch := range rest {
			if (ch >= '0' && ch <= '9') || ch == '.' {
				ver += string(ch)
			} else {
				break
			}
		}
		if ver != "" {
			return ver
		}
	}
	return ""
}

func writeRegistrySection(b *strings.Builder, components map[string]map[string]interface{}) {
	b.WriteString("## Base Image Registry Distribution\n\n")

	registries := map[string]int{}
	for _, data := range components {
		for _, df := range getSlice(data, "dockerfiles") {
			img := getStr(df, "base_image", "")
			if strings.Contains(img, "/") {
				reg := strings.SplitN(img, "/", 2)[0]
				if strings.Contains(reg, ".") || strings.Contains(reg, ":") {
					registries[reg]++
				} else {
					registries["(docker.io implicit)"]++
				}
			} else if strings.HasPrefix(img, "$") {
				registries["(build variable)"]++
			} else if img != "" {
				registries["(build stage ref)"]++
			}
		}
	}

	type kv struct {
		k string
		v int
	}
	var sorted []kv
	for k, v := range registries {
		sorted = append(sorted, kv{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].v > sorted[j].v })

	b.WriteString("| Registry | Count |\n|----------|-------|\n")
	for _, s := range sorted {
		b.WriteString(fmt.Sprintf("| `%s` | %d |\n", s.k, s.v))
	}
	b.WriteString("\n")
}

func writeMultiArchSection(b *strings.Builder, components map[string]map[string]interface{}, names []string) {
	b.WriteString("## Multi-Architecture Support\n\n")

	count := 0
	for _, data := range components {
		for _, df := range getSlice(data, "dockerfiles") {
			if len(getStringSlice(df, "architectures")) > 0 {
				count++
			}
		}
	}
	b.WriteString(fmt.Sprintf("**%d** Dockerfiles declare multi-architecture support.\n\n", count))
	b.WriteString("| Component | Dockerfile | Architectures | Stages | User |\n")
	b.WriteString("|-----------|-----------|---------------|--------|------|\n")

	for _, name := range names {
		for _, df := range getSlice(components[name], "dockerfiles") {
			archs := getStringSlice(df, "architectures")
			if len(archs) > 0 {
				user := getStr(df, "user", "(not set)")
				b.WriteString(fmt.Sprintf("| %s | `%s` | %s | %d | `%s` |\n",
					name, getStr(df, "path", ""), strings.Join(archs, ", "), getInt(df, "stages"), user))
			}
		}
	}
	b.WriteString("\n")
}

func writeDockerfileIssuesSection(b *strings.Builder, components map[string]map[string]interface{}, names []string) {
	b.WriteString("## Dockerfile Security & Quality Issues\n\n")

	issuesByType := map[string]int{}
	total := 0
	for _, data := range components {
		for _, df := range getSlice(data, "dockerfiles") {
			for _, issue := range getStringSlice(df, "issues") {
				total++
				key := issue
				if idx := strings.Index(issue, ":"); idx > 0 && idx < 30 {
					key = issue[:idx]
				}
				issuesByType[key]++
			}
		}
	}

	b.WriteString(fmt.Sprintf("**%d issues** across all Dockerfiles.\n\n", total))
	b.WriteString("| Issue Type | Count |\n|-----------|-------|\n")
	type kv struct {
		k string
		v int
	}
	var sorted []kv
	for k, v := range issuesByType {
		sorted = append(sorted, kv{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].v > sorted[j].v })
	for _, s := range sorted {
		b.WriteString(fmt.Sprintf("| %s | %d |\n", s.k, s.v))
	}

	b.WriteString("\n| Component | Dockerfile | Issue |\n|-----------|-----------|-------|\n")
	for _, name := range names {
		for _, df := range getSlice(components[name], "dockerfiles") {
			for _, issue := range getStringSlice(df, "issues") {
				b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n", name, getStr(df, "path", ""), issue))
			}
		}
	}
	b.WriteString("\n")
}

func writeSecurityContextSection(b *strings.Builder, components map[string]map[string]interface{}, names []string) {
	b.WriteString("## Container Security Contexts\n\n")

	totalC, missingSC := 0, 0
	for _, data := range components {
		for _, dep := range getSlice(data, "deployments") {
			for _, c := range getSlice(dep, "containers") {
				totalC++
				if getMap(c, "security_context") == nil {
					missingSC++
				}
			}
		}
	}

	b.WriteString(fmt.Sprintf("**%d/%d** containers have no security context defined.\n\n", missingSC, totalC))
	b.WriteString("| Component | Deployment | Container | RunAsNonRoot | ReadOnlyFS | Privileged | Drop ALL |\n")
	b.WriteString("|-----------|-----------|-----------|:-----------:|:---------:|:---------:|:--------:|\n")

	for _, name := range names {
		for _, dep := range getSlice(components[name], "deployments") {
			for _, c := range getSlice(dep, "containers") {
				sc := getMap(c, "security_context")
				if sc == nil {
					b.WriteString(fmt.Sprintf("| %s | %s | %s | - | - | - | **NONE** |\n",
						name, getStr(dep, "name", ""), getStr(c, "name", "")))
					continue
				}
				ran := fmtBoolField(sc, "runAsNonRoot")
				rofs := fmtBoolField(sc, "readOnlyRootFilesystem")
				priv := fmtBoolFieldInverse(sc, "privileged")
				caps := getMap(sc, "capabilities")
				drop := "**No**"
				if caps != nil {
					for _, d := range getStringSlice(caps, "drop") {
						if d == "ALL" {
							drop = "Yes"
						}
					}
				}
				b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s |\n",
					name, getStr(dep, "name", ""), getStr(c, "name", ""), ran, rofs, priv, drop))
			}
		}
	}
	b.WriteString("\n")
}

func writeResourceLimitsSection(b *strings.Builder, components map[string]map[string]interface{}, names []string) {
	b.WriteString("## Container Resource Limits\n\n")

	totalC, noLimits := 0, 0
	for _, data := range components {
		for _, dep := range getSlice(data, "deployments") {
			for _, c := range getSlice(dep, "containers") {
				totalC++
				if getMap(c, "resources") == nil {
					noLimits++
				}
			}
		}
	}

	b.WriteString(fmt.Sprintf("**%d/%d** containers have no resource limits.\n\n", noLimits, totalC))
	b.WriteString("| Component | Deployment | Container | CPU Req | CPU Lim | Mem Req | Mem Lim |\n")
	b.WriteString("|-----------|-----------|-----------|---------|---------|---------|--------|\n")

	for _, name := range names {
		for _, dep := range getSlice(components[name], "deployments") {
			for _, c := range getSlice(dep, "containers") {
				res := getMap(c, "resources")
				if res == nil {
					b.WriteString(fmt.Sprintf("| %s | %s | %s | **-** | **-** | **-** | **-** |\n",
						name, getStr(dep, "name", ""), getStr(c, "name", "")))
					continue
				}
				req := getMap(res, "requests")
				lim := getMap(res, "limits")
				b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s |\n",
					name, getStr(dep, "name", ""), getStr(c, "name", ""),
					mapVal(req, "cpu"), mapVal(lim, "cpu"), mapVal(req, "memory"), mapVal(lim, "memory")))
			}
		}
	}
	b.WriteString("\n")
}

func writeHealthProbeSection(b *strings.Builder, components map[string]map[string]interface{}, names []string) {
	b.WriteString("## Health Probes\n\n")

	totalC := 0
	noLiveness, noReadiness := 0, 0
	for _, data := range components {
		for _, dep := range getSlice(data, "deployments") {
			for _, c := range getSlice(dep, "containers") {
				totalC++
				if getMap(c, "liveness_probe") == nil {
					noLiveness++
				}
				if getMap(c, "readiness_probe") == nil {
					noReadiness++
				}
			}
		}
	}

	b.WriteString(fmt.Sprintf("**%d/%d** missing liveness. **%d/%d** missing readiness.\n\n", noLiveness, totalC, noReadiness, totalC))
	b.WriteString("| Component | Deployment | Container | Liveness | Readiness |\n")
	b.WriteString("|-----------|-----------|-----------|----------|----------|\n")

	for _, name := range names {
		for _, dep := range getSlice(components[name], "deployments") {
			for _, c := range getSlice(dep, "containers") {
				lp := getMap(c, "liveness_probe")
				rp := getMap(c, "readiness_probe")
				liveness := "**MISSING**"
				readiness := "**MISSING**"
				if lp != nil {
					liveness = fmt.Sprintf("`%s %s`", getStr(lp, "type", ""), getStr(lp, "path", ""))
				}
				if rp != nil {
					readiness = fmt.Sprintf("`%s %s`", getStr(rp, "type", ""), getStr(rp, "path", ""))
				}
				b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
					name, getStr(dep, "name", ""), getStr(c, "name", ""), liveness, readiness))
			}
		}
	}
	b.WriteString("\n")
}

func writeSidecarSection(b *strings.Builder, components map[string]map[string]interface{}, names []string) {
	b.WriteString("## Sidecar Containers\n\n")
	b.WriteString("| Component | Deployment | Main | Sidecars |\n")
	b.WriteString("|-----------|-----------|------|----------|\n")

	for _, name := range names {
		for _, dep := range getSlice(components[name], "deployments") {
			containers := getSlice(dep, "containers")
			if len(containers) > 1 {
				var cNames []string
				for _, c := range containers {
					cNames = append(cNames, getStr(c, "name", ""))
				}
				b.WriteString(fmt.Sprintf("| %s | %s | `%s` | %s |\n",
					name, getStr(dep, "name", ""), cNames[0],
					strings.Join(wrapBackticks(cNames[1:]), ", ")))
			}
		}
	}
	b.WriteString("\n")
}

func writeDeploymentIssuesSection(b *strings.Builder, components map[string]map[string]interface{}) {
	b.WriteString("## Deployment Issues\n\n")

	issues := map[string]int{}
	for _, data := range components {
		for _, dep := range getSlice(data, "deployments") {
			for _, issue := range getStringSlice(dep, "issues") {
				issues[issue]++
			}
		}
	}

	b.WriteString("| Issue | Count |\n|-------|-------|\n")
	type kv struct {
		k string
		v int
	}
	var sorted []kv
	for k, v := range issues {
		sorted = append(sorted, kv{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].v > sorted[j].v })
	for _, s := range sorted {
		b.WriteString(fmt.Sprintf("| %s | %d |\n", s.k, s.v))
	}
	b.WriteString("\n")
}

func writeImageConstantsSection(b *strings.Builder, components map[string]map[string]interface{}, names []string) {
	b.WriteString("## Operator Image Constants\n\n")
	b.WriteString("| Component | Constant | Default Value |\n")
	b.WriteString("|-----------|----------|---------------|\n")

	for _, name := range names {
		for _, cfg := range getSlice(components[name], "operator_config") {
			cat := getStr(cfg, "category", "")
			cname := getStr(cfg, "name", "")
			if cat != "image" && !strings.Contains(strings.ToLower(cname), "image") {
				continue
			}
			b.WriteString(fmt.Sprintf("| %s | `%s` | `%s` |\n",
				name, cname, truncate(getStr(cfg, "value", ""), 70)))
		}
	}
	b.WriteString("\n")
}

// Helpers

func sortedKeys(m map[string]map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}

func fmtBoolField(m map[string]interface{}, key string) string {
	v, ok := m[key]
	if !ok {
		return "-"
	}
	if b, ok := v.(bool); ok {
		if b {
			return "Yes"
		}
		return "**No**"
	}
	return "-"
}

func fmtBoolFieldInverse(m map[string]interface{}, key string) string {
	v, ok := m[key]
	if !ok {
		return "-"
	}
	if b, ok := v.(bool); ok {
		if b {
			return "**Yes**"
		}
		return "No"
	}
	return "-"
}

func mapVal(m map[string]interface{}, key string) string {
	if m == nil {
		return "-"
	}
	v, ok := m[key]
	if !ok {
		return "-"
	}
	return fmt.Sprintf("%v", v)
}

func wrapBackticks(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = "`" + s + "`"
	}
	return out
}

func getStr(m map[string]interface{}, key, fallback string) string {
	if m == nil {
		return fallback
	}
	v, ok := m[key]
	if !ok {
		return fallback
	}
	s, ok := v.(string)
	if !ok {
		return fallback
	}
	return s
}

func getMap(m map[string]interface{}, key string) map[string]interface{} {
	if m == nil {
		return nil
	}
	v, ok := m[key]
	if !ok {
		return nil
	}
	mm, ok := v.(map[string]interface{})
	if ok {
		return mm
	}
	return nil
}

func getSlice(m map[string]interface{}, key string) []map[string]interface{} {
	if m == nil {
		return nil
	}
	v, ok := m[key]
	if !ok {
		return nil
	}
	switch typed := v.(type) {
	case []map[string]interface{}:
		return typed
	case []interface{}:
		out := make([]map[string]interface{}, 0, len(typed))
		for _, item := range typed {
			if mm, ok := item.(map[string]interface{}); ok {
				out = append(out, mm)
			}
		}
		return out
	}
	return nil
}

func getStringSlice(m map[string]interface{}, key string) []string {
	if m == nil {
		return nil
	}
	v, ok := m[key]
	if !ok {
		return nil
	}
	switch typed := v.(type) {
	case []string:
		return typed
	case []interface{}:
		out := make([]string, 0, len(typed))
		for _, item := range typed {
			if s, ok := item.(string); ok {
				out = append(out, s)
			}
		}
		return out
	}
	return nil
}

func getInt(m map[string]interface{}, key string) int {
	if m == nil {
		return 0
	}
	v, ok := m[key]
	if !ok {
		return 0
	}
	switch n := v.(type) {
	case float64:
		return int(n)
	case int:
		return n
	}
	return 0
}
